name: 🐞 Bug Report
description: File a bug report to help us improve the project
title: "[BUG] <short description>"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.  
        Please fill out the details below as completely as possible.  
        This helps us reproduce and fix the issue faster.  

  - type: input
    id: summary
    attributes:
      label: 🔎 Bug Summary
      description: Provide a clear, one-sentence summary of the bug.
      placeholder: "Program crashes when..."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 🐞 Detailed Description
      description: A more detailed explanation of the bug.
      placeholder: "When I try to create a sphere..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: ✅ Steps to Reproduce
      description: Step-by-step instructions to reproduce the behavior.
      placeholder: |
        1. Create an instance of Term3D
        2. Create a large sphere
        3. Attach a cube to it
        4. ...and the program crashes
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 🤔 Expected Behavior
      description: What you expected to happen instead.
      placeholder: "The program should handle this flawlessly."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 💥 Actual Behavior
      description: What actually happens, including any error messages.
      placeholder: "The program crashes."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📷 Screenshots or Logs
      description: Upload screenshots or copy-paste error logs that show the issue.
      placeholder: "Paste logs here or drag & drop screenshots."

  - type: dropdown
    id: severity
    attributes:
      label: ⚠️ Severity
      description: How badly does this bug affect you?
      options:
        - "🟢 Minor – cosmetic issue, no impact on functionality"
        - "🟡 Moderate – affects some features but has a workaround"
        - "🔴 Major – breaks core functionality, no workaround"
        - "🔥 Critical – prevents any use of the project"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Describe your environment (OS, Python version, etc.).
      placeholder: "Windows 11, CPython 3.11.9, using Windows Subsystem for Linux (WSL)"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📌 Affected Version
      description: Which version of the project are you using? (commit hash, release tag, or current)
      placeholder: "e.g., 4eb9a2 / v0.0.1 / current"
    validations:
      required: true

  - type: checkboxes
    id: reproducibility
    attributes:
      label: 🔄 Reproducibility
      description: How often does this bug occur?
      options:
        - label: "Always"
        - label: "Often"
        - label: "Sometimes"
        - label: "Rarely"
        - label: "Only once"

  - type: textarea
    id: workarounds
    attributes:
      label: 🛠️ Workarounds
      description: Do you have a temporary fix or workaround?
      placeholder: "Using the legacy mesh temporarily fixes the issue, but it is no longer supported in this version."

  - type: textarea
    id: context
    attributes:
      label: 📌 Additional Context
      description: Any other context or info that could help us investigate.
      placeholder: "This happens only when the mesh is very large."
