name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tools
        run: |
          pip install ruff black isort reviewdog


      - name: Ruff lint
        run: |
          ruff check . --output-format=github | reviewdog -f=github-pr-check -reporter=github-pr-review -fail-on-error=true

      - name: Black check
        run: |
          black --check --diff . | reviewdog -f=diff -reporter=github-pr-review -fail-on-error=true

      - name: isort check
        run: |
          isort --check-only --diff . | reviewdog -f=diff -reporter=github-pr-review -fail-on-error=true