name: Auto Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  auto-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed so we can push formatting fixes
      pull-requests: write  # needed if you want it to update PRs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install formatters
        run: pip install black isort

      - name: Run auto-formatters
        run: |
          black .
          isort .

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "style: auto-format with black & isort"
            git push
          fi
