name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort reviewdog

      # -----------------------------
      # BLACK (formatter check)
      # -----------------------------
      - name: Run black with reviewdog
        run: |
          set -o pipefail
          black --check --diff . | reviewdog -f=diff \
            -name=black \
            -reporter=github-pr-review \
            -fail-on-error=true || true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # -----------------------------
      # ISORT (import sorting check)
      # -----------------------------
      - name: Run isort with reviewdog
        run: |
          set -o pipefail
          isort --check-only --diff . | reviewdog -f=diff \
            -name=isort \
            -reporter=github-pr-review \
            -fail-on-error=true || true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
