name: Lint Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Install dependencies
      - name: Install linters
        run: |
          pip install black isort

      # Install reviewdog (not pip!)
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      # Run Black (check only, no changes)
      - name: Run Black
        run: |
          black --check --diff . | reviewdog -f=diff -name=black -reporter=github-pr-review -fail-on-error=true

      # Run isort (check only)
      - name: Run isort
        run: |
          isort --check-only --diff . | reviewdog -f=diff -name=isort -reporter=github-pr-review -fail-on-error=true
