name: Lint

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      # Black check
      - name: Run black
        run: black --check --diff .

      # isort check
      - name: Run isort
        run: isort --check-only --diff .

      # Setup reviewdog
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      # Report black issues via reviewdog
      - name: Black lint (reviewdog)
        run: |
          black --check --diff . | reviewdog -f=diff \
            -name=black \
            -reporter=github-pr-review \
            -level=error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Report isort issues via reviewdog
      - name: isort lint (reviewdog)
        run: |
          isort --check-only --diff . | reviewdog -f=diff \
            -name=isort \
            -reporter=github-pr-review \
            -level=error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
