name: Quick Test Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  run-tests:
    # Use a strategy matrix to run the job on multiple operating systems.
    strategy:
      fail-fast: false # Ensure all jobs complete even if one fails
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    # The job will run on the OS specified in the matrix.
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Note: On Windows, the "Temporarily move test files" and "Move files back" steps
      # need to use different commands. This is handled by a condition on the step.
      - name: Temporarily move test files (Linux/macOS)
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        run: |
          if [ -d "tests" ]; then
            mv tests/* .
          fi

      - name: Temporarily move test files (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: pwsh # Use PowerShell for Windows commands
        run: |
          if (Test-Path -Path "tests" -PathType Container) {
            Move-Item -Path "tests\*" -Destination "."
          }

      - name: Run all tests with timeout
        id: run_tests
        # On Windows, use `cmd.exe` as the shell for the `timeout` command.
        shell: ${{ startsWith(matrix.os, 'windows') && 'cmd' || 'bash' }}
        run: |
          echo "" > raw_output.txt
          error_found=0
          for file in *.py; do
            echo "Running $file..."
            if ! timeout 10s python3 "$file" >> raw_output.txt 2>&1; then
              if [ $? -eq 124 ]; then
                echo "[TIMEOUT] $file" >> raw_output.txt
              else
                echo "[ERROR] $file" >> raw_output.txt
              fi
              error_found=1
            else
              echo "[OK] $file" >> raw_output.txt
            fi
          done
          echo "error_found=$error_found" >> $GITHUB_ENV

      - name: Move files back (cleanup)
        if: always() && (startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos'))
        run: |
          if [ -d "tests" ]; then
            mkdir -p tests
            for file in *.py; do
              mv "$file" tests/
            done
          fi
      
      - name: Move files back (cleanup - Windows)
        if: always() && startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          if (Test-Path -Path "tests" -PathType Container) {
            Get-ChildItem -Path *.py | ForEach-Object {
              Move-Item -Path $_.FullName -Destination "tests\"
            }
          }

      - name: Upload full logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: full-test-logs-${{ matrix.os }} # Name artifact uniquely for each OS
          path: raw_output.txt

      - name: Post comment result
        # Only post the comment from one job to avoid duplicate comments.
        if: always() && matrix.os == 'ubuntu-latest'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const issue_number = context.payload.pull_request.number;
            const logs = fs.readFileSync('raw_output.txt', 'utf8');
            let summary = '### ✅ Test Results:\n';

            logs.split('\n').forEach(line => {
              if (line.startsWith('[OK]')) {
                const file = line.replace('[OK] ', '');
                summary += `✅ ${file}\n`;
              } else if (line.startsWith('[ERROR]')) {
                const file = line.replace('[ERROR] ', '');
                summary += `❌ ${file}\n`;
              } else if (line.startsWith('[TIMEOUT]')) {
                const file = line.replace('[TIMEOUT] ', '');
                summary += `⏳ ${file}\n`;
              }
            });

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              body: summary
            });
